- name: Configure Warewulf Head Node
  hosts: head
  become: true
  tasks:

- name: Build Node Image
  hosts: head
  become: true
  tasks:
    - name: Generate compute node image
      environment:
        container: "{{ warewulf_container }}"
      ansible.builtin.shell: |-
        set -e -x
        export LANG=C.UTF-8

        ## Config
        sms_ip=10.5.0.8
        : ${container:=docker://ghcr.io/warewulf/warewulf-rockylinux:9}

        ## Import node image from container
        wwctl image delete nodeimage --yes || /bin/true
        wwctl image import $container nodeimage --syncuser

        ## Configure profile
        wwctl profile set --yes nodes --image=nodeimage
        wwctl profile set --yes nodes --kernelargs='console=tty0,"console=ttyS0,115200",crashkernel=no,systemd.log_color=0'
        wwctl profile set --yes nodes --netname=default --netdev=eth0

        ## Configure image
        wwctl image exec nodeimage /bin/bash << EXEC
        set -e -x
        set -o pipefail

        ## Setup base OS
        dnf install -y dnf-plugins-core
        dnf config-manager --set-enabled crb
        dnf install -y epel-release
        dnf install -y --allowerasing python3 ca-certificates procps wget curl unzip jq passwd

        ## Update Image
        dnf upgrade -y

        ## Remove old kernels
        dnf repoquery --installonly --latest-limit=-1 -q | xargs dnf remove -y

        ## Debug
        passwd -d root # allow serial console login

        ## Install compute node packages
        dnf install -y slurm-slurmd munge chrony

        ## Enable services
        systemctl enable munge
        systemctl enable slurmd

        ## Configure node
        echo "server ${sms_ip} iburst" >> /etc/chrony.conf
        echo SLURMD_OPTIONS="--conf-server ${sms_ip}" > /etc/sysconfig/slurmd

        ## Extras
        dnf install -y Lmod

        ## Cleanup
        dnf clean all
        EXEC

      args:
        creates: /var/lib/warewulf/provision/image/nodeimage.img.gz
