- name: Configure Warewulf Head Node
  hosts: head
  become: true
  tasks:

- name: Build Rocky Image
  hosts: head
  become: true
  tasks:
    - name: Generate compute node image
      ansible.builtin.shell: |
        set -e

        ## Config
        sms_ip=10.5.0.8

        ## Import node image from Warewulf
        wwctl image import docker://ghcr.io/warewulf/warewulf-rockylinux:9 rocky-9

        wwctl image exec rocky-9 /bin/bash <<EOF
          set -e

          ## Mirror
          export YUM_MIRROR_BASE=https://mirror.usi.edu/pub/rocky # optional mirror

          ## Debug
          passwd -d root # allow serial console login

          ## Setup base OS
          dnf install -y dnf-plugins-core
          dnf config-manager --set-enabled crb
          dnf install -y epel-release
          dnf install -y --allowerasing python3 ca-certificates procps wget curl unzip jq

          ## Update Image
          dnf upgrade -y

          ## Install Kernel
          dnf install -y kernel

          ## Allocate static UID:120 GID:120 for munge
          groupadd --system -g 120 munge
          useradd --system -u 120 -g 120 -d /run/munge -s /sbin/nologin -c "Runs Uid N Gid Emporium" munge

          ## Install compute node packages
          dnf install -y slurm-slurmd munge chrony

          ## Enable services
          systemctl enable munge
          systemctl enable slurmd

          ## Configure node
          echo "server ${sms_ip} iburst" >> /etc/chrony.conf
          echo SLURMD_OPTIONS="--conf-server ${sms_ip}" > /etc/sysconfig/slurmd

          ## Extras
          dnf install -y Lmod

          ## Cleanup
          dnf clean all
        EOF

        ## Set profile
        wwctl profile set --yes nodes --image rocky-9
        wwctl profile set --yes nodes --kernelargs='"console=tty0","console=ttyS0,115200","crashkernel=no","systemd.log_color=0"'
        wwctl profile set --yes nodes --netname default --netdev eth0

      args:
        creates: /var/lib/warewulf/provision/image/rocky-9.img.gz
