- name: Build Ubuntu Image
  hosts: head
  become: true
  tasks:
    - name: Generate compute node image
      ansible.builtin.shell: |
        set -e

        ## Config
        sms_ip=10.5.0.8

        ## Import node image
        wwctl image import docker://registry.docker.com/library/ubuntu:24.04 ubuntu-24.04
        wwctl image syncuser ubuntu-24.04 --write # set head uid/gid in image before install

        ## Build and configure node
        wwctl image exec --syncuser ubuntu-24.04 /bin/bash <<EOF
          set -e

          ## Debug
          passwd -d root # allow serial console login

          ## Update image
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install --yes apt-utils
          apt-get dist-upgrade --yes

          ## Install kernel
          apt-get install --yes --no-install-recommends linux-image-generic linux-tools-generic
          rm -vf /initrd.img* /vmlinuz*

          ## Install base packages
          apt-get install --yes --no-install-recommends curl jq zstd cpio procps iproute2 busybox-static
          apt-get install --yes --no-install-recommends init udev dbus polkitd
          apt-get install --yes --no-install-recommends systemd-timesyncd systemd-resolved ifupdown
          apt-get install --yes --no-install-recommends openssh-server python3
          apt-get install --yes less vim

          ## Network
          #systemctl enable systemd-networkd

          ## Munge
          mount -t devpts devpts /dev/pts ## FIXME: workarround
          install -dv --mode=700 --owner=munge --group=munge /etc/munge
          touch /etc/munge/munge.key ## blank file will be replace with the overlay (bypass image install error)
          apt-get install --yes munge
          systemctl enable munge
          umount /dev/pts ## workarround

          ## Slurm
          apt-get install --yes slurmd
          echo SLURMD_OPTIONS="--conf-server ${sms_ip}" > /etc/default/slurmd
          systemctl enable slurmd

          ## Lmod
          apt-get install --yes lmod

          ## Cleanup and exit
          apt-get clean
          echo "exit image"
        EOF

        ## Set profile
        wwctl profile set --yes nodes --image=ubuntu-24.04
        wwctl profile set --yes nodes --kernelargs='console=tty0,"console=ttyS0,115200",crashkernel=no,systemd.log_color=0'
        wwctl profile set --yes nodes --netname=default --netdev=en0

      args:
        creates: /var/lib/warewulf/provision/image/ubuntu-24.04.img.gz
