- name: Add Nodes
  hosts: head
  become: true
  tasks:
    - name: Configure node provisioning
      # noqa: risky-shell-pipe
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |-
          set -e -x

          for I in {1..4} ; do
            IP=10.5.1.$I
            NODE=c$I
            MAC=""
            ping -q -c 4 -W 0.2 -i 0.2 $IP > /dev/null || /bin/true
            MAC=$(ip -json neigh | jq -r ".[] | select(.dst == \"${IP}\").lladdr")
            wwctl node delete --yes $NODE || /bin/true
            echo $IP $NODE $MAC
            wwctl node add $NODE --profile=nodes --netname=default --ipaddr=$IP
            if [[ "${MAC}" != "null" ]] ; then
              wwctl node set --yes $NODE --hwaddr=$MAC
            fi
          done

          wwctl overlay build
          wwctl configure --all

          ## Nodes show up in /etc/hosts after `wwctl configure --all`
          scontrol reconfigure
          sinfo

          touch /root/add-nodes.stamp

      args:
        creates: /root/add-node.stamp
