- name: Add Nodes
  hosts: head
  become: true
  tasks:
    - name: Configure node provisioning
      # noqa: risky-shell-pipe
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          IMAGE_NAME={{ image_name }}

          for I in {0..4} ; do
            IP=10.5.1.$I
            NODE=c$I
            MAC=""
            ping -q -c 1 -W 0.2 $IP
            MAC=$(ip -json neigh | jq -r ".[] | select(.dst == \"${IP}\").lladdr")
            wwctl node delete -y $NODE
            if [[ "${MAC}" != "null" ]] ; then
              echo $IP $NODE $MAC
              wwctl node add $NODE
              wwctl node set -y --container $IMAGE_NAME $NODE
              wwctl node set -y --ipaddr $IP --hwaddr $MAC $NODE
            fi
          done

          wwctl node set --yes --kernelargs="crashkernel=no vga=791 net.naming-scheme=v238" 'c[0-4]'

          wwctl configure --all
          wwctl overlay build

          touch /root/add-nodes.stamp

      args:
        creates: /root/add-node.stamp
