- name: Configure System
  hosts: head
  become: true
  tasks:

    - name: Upgrade all packages
      ansible.builtin.apt:
        name: '*'
        state: latest # noqa package-latest

    - name: Prep base systems
      ansible.builtin.apt:
        name:
          - apt-utils

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: needs_reboot

    - name: Reboot system
      ansible.builtin.reboot:
      when: needs_reboot.stat.exists
