- name: Test Playbook
  hosts: localhost
  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: Variables
      ansible.builtin.lineinfile:
        path: test.json
        create: true
        mode: '0600'
        line: '"{{ warewulf_rpm }}"'
      when: not ohpc_warewulf
