- name: Configure Warewulf Head Node
  hosts: head
  become: true
  tasks:

    - name: Install base packages (apt)
      ansible.builtin.apt:
        name:
          - ca-certificates
          - git
          - curl
      when: ansible_pkg_mgr == "apt"

    - name: Install Warewulf dependencies (apt)
      ansible.builtin.apt:
        name:
          - unzip
          - golang
          - chrony
          - isc-dhcp-server
          - tftpd-hpa
          - ipxe
          - nfs-kernel-server
          - slurmd
          - slurmctld
          - openmpi-bin
      when: ansible_pkg_mgr == "apt"

    - name: Install base packages (dnf)
      ansible.builtin.dnf:
        name:
          - epel-release
          - ca-certificates
          - git
          - curl
      when: ansible_pkg_mgr == "dnf"

    - name: Install Warewulf build dependencies (dnf)
      ansible.builtin.dnf:
        name:
          - unzip
          - golang
          - chrony
          - dhcp-server
          - tftp-server
          - ipxe-bootimgs-x86
          - ipxe-bootimgs-aarch64
          - slurm-slurmd
          - slurm-slurmctld
      when: ansible_pkg_mgr == "dnf"

    - name: Add head localnet to chrony
      ansible.builtin.lineinfile:
        path: "{{ '/etc/chrony/chrony.conf' if ansible_os_family == 'Debian' else '/etc/chrony.conf' }}"
        line: "allow 10.5.0.0/16"
      register: chrony_conf

    - name: Restart chrony
      # noqa: no-handler
      ansible.builtin.systemd_service:
        name: chronyd.service
        enabled: true
        state: restarted
      when: chrony_conf.changed

    - name: Build Warewulf from source
      # noqa: command-instead-of-module
      ansible.builtin.shell: |
        set -e

        cd /usr/src
        git clone https://github.com/warewulf/warewulf.git
        cd warewulf
        make clean defaults \
          PREFIX=/usr \
          BINDIR=/usr/bin \
          SYSCONFDIR=/etc \
          DATADIR=/usr/share \
          LOCALSTATEDIR=/var/lib \
          SHAREDSTATEDIR=/var/lib \
          MANDIR=/usr/share/man \
          INFODIR=/usr/share/info \
          DOCDIR=/usr/share/doc \
          SRVDIR=/var/lib \
          TFTPDIR=/srv/tftp \
          SYSTEMDDIR=/usr/lib/systemd/system \
          BASHCOMPDIR=/etc/bash_completion.d/ \
          FIREWALLDDIR=/usr/lib/firewalld/services \
          WWCLIENTDIR=/warewulf
        make all
        make install

      args:
        creates: /usr/bin/wwctl

    - name: WW4 warewulf.conf
      ansible.builtin.template:
        src: templates/warewulf.conf.j2
        dest: /etc/warewulf/warewulf.conf
        mode: "600"

    - name: WW4 defaults.conf
      ansible.builtin.template:
        src: templates/defaults.conf.j2
        dest: /etc/warewulf/defaults.conf
        mode: "600"

    - name: Setup the head node
      # noqa: command-instead-of-module
      ansible.builtin.shell: |
        set -e

        ## Config
        sms_name=head

        ## Warewulf
        wwctl configure --all
        wwctl configure hostfile
        wwctl configure ssh
        wwctl configure nfs

        ## Slurm
        # Use /etc/warewulf/examples/slurm.conf.ww - templated.... (do it the warewulf way)
        cp -v /usr/share/doc/slurmd/examples/slurm.conf.simple /etc/slurm/slurm.conf

        perl -pi -e "s/^SlurmctldHost=.*/SlurmctldHost=${sms_name}/" /etc/slurm/slurm.conf
        grep '^SlurmctldHost=' /etc/slurm/slurm.conf

        perl -pi -e 's/^NodeName=.*$/NodeName=c[0-4] State=UNKNOWN/' /etc/slurm/slurm.conf
        grep '^NodeName' /etc/slurm/slurm.conf

        perl -pi -e 's/^PartitionName=.*$/PartitionName=normal Nodes=c[0-4] Default=YES/' /etc/slurm/slurm.conf
        grep '^PartitionName' /etc/slurm/slurm.conf

        grep 'SlurmctldParameters=' /etc/slurm/slurm.conf || echo 'SlurmctldParameters=enable_configless' >> /etc/slurm/slurm.conf
        grep 'SlurmctldParameters=' /etc/slurm/slurm.conf

        ## Start head node services
        systemctl enable --now warewulfd
        systemctl enable --now munge
        systemctl enable --now slurmctld

        ## Configure warewulf default profile for network
        wwctl profile set -y default --netmask 255.255.0.0

        ## Configure boot
        cp -v /usr/lib/ipxe/snponly.efi /srv/tftp/warewulf/ipxe-snponly-x86_64.efi

        touch /root/head.stamp

      args:
        creates: /root/head.stamp

- name: Setup compute nodes
  hosts: head
  become: true
  tasks:
    - name: Generate compute node image
      ansible.builtin.shell: |
        set -e
        sms_ip=10.5.0.8

        ## Import node image
        wwctl container import docker://registry.docker.com/library/ubuntu:24.04 ubuntu-24.04
        wwctl container syncuser ubuntu-24.04 --write # set head uid/gid in container before install
        wwctl overlay build

        ## Build and configure node
        wwctl container exec ubuntu-24.04 /bin/bash <<EOF

        ## Update image
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install --yes apt-utils
        apt-get dist-upgrade --yes

        ## Configure Image
        passwd -d root # allow serial console login

        ## Install kernel
        apt-get install --yes --no-install-recommends linux-image-generic linux-tools-generic
        rm -v /initrd.img* /vmlinuz*

        ## Install base packages
        apt-get install --yes --no-install-recommends curl jq zstd cpio procps iproute2 busybox-static
        apt-get install --yes --no-install-recommends init udev dbus polkitd
        apt-get install --yes --no-install-recommends systemd-timesyncd systemd-resolved
        apt-get install --yes --no-install-recommends openssh-server python3
        apt-get install --yes less vim

        ## Network
        systemctl enable systemd-networkd
        cat > /etc/systemd/network/en.network <<CONF
        [Match]
        Name=en*

        [Network]
        DHCP=yes
        LinkLocalAddressing=ipv6
        CONF

        wwctl overlay mkdir wwinit /etc/systemd/network
        wwctl overlay import wwinit en.network /etc/systemd/network/en.network

        mount -t devpts devpts /dev/pts ## workarround
        install -dv --mode=700 --owner=munge --group=munge /etc/munge
        touch /etc/munge/munge.key ## blank file will be replace with the overlay (bypass container install error)
        apt-get install --yes munge
        systemctl enable munge
        umount /dev/pts ## workarround

        apt-get install --yes slurmd
        echo SLURMD_OPTIONS="--conf-server ${sms_ip}" > /etc/default/slurmd
        systemctl enable slurmd

        apt-get install --yes lmod

        ## Cleanup
        apt-get clean

        echo "exit container"
        EOF

        ## fix init hack
        perl -pi -e 's/#!\/bin\/sh/\/bin\/bash/' /var/lib/warewulf/overlays/wwinit/rootfs/init

        wwctl overlay mkdir generic --mode 0700 /etc/munge
        wwctl overlay import generic /etc/munge/munge.key
        wwctl overlay chown generic /etc/munge/munge.key $(id -u munge) $(id -g munge)
        wwctl overlay chown generic /etc/munge $(id -u munge) $(id -g munge)

        useradd --create-home --shell=/bin/bash --user-group auser
        wwctl container syncuser ubuntu-24.04 --write --build
        wwctl overlay build

        touch /root/configure-node-image.stamp

      args:
        creates: /root/configure-node-image.stamp
