name: ci-test
on:
  push:
    branches: [ ci ]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: install packages
        run: |-
          sudo apt install -y python3-openstackclient
          openstack --version
